name: Cargo license check
on: pull_request
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2.0.11
      with:
        manifest-path: "Cargo.toml"
        command: check
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
